version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
  target-branch: main
  labels:
  - dependency_updates
- package-ecosystem: docker
  directory: "/.docker"
  schedule:
    interval: weekly
  open-pull-requests-limit: 50
  target-branch: main
  labels:
  - dependency_updates
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  target-branch: main
  labels:
  - CI
