version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
  target-branch: master
  labels:
  - dependency_updates
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 50
  target-branch: master
  labels:
  - dependency_updates
