default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Blacken

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
      exclude: README.md
    - id: check-yaml
    - id: check-json
    - id: end-of-file-fixer
